version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_PROTOCOL: http
      NGROK_PORT: backend:3000
    ports:
      - "4040:4040"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
